### ISSUE TITLE
HLS playback laggy with the wpf control.

### ISSUE THREAD

**Issue by moolicc** [unosquare/ffplaydotnet#6]
So, using https://github.com/Tyrrrz/YoutubeExplode with the wpf control, I was hoping to playback live streaming youtube. But unfortunately the wpf control seems to lag. I don't think it's internet speed related because youtube never buffers and I have 64 Mbps down. I've uploaded a gif, notice the rotating satellite dish.
https://imgur.com/3J1tVkm

The control being behind the playback of youtube is fine for me, but the stopping/starting won't work out I'm afraid. It's probably just something I'm missing. Ideas/thoughts? 

Thanks!

**Comment by moolicc** [comment]
Sorry, just noticed the "Repo has moved" notice.

**Comment by mariodivece** [comment]
Yep. Make sure you post any issue over there (ffmediaelement)

**Comment by moolicc** [comment]
Yeah, I think https://github.com/unosquare/ffmediaelement/issues/110 is the same problem that I was experiencing. Not sure though, to be honest. This is kind of stuff is way out of my scope.
